<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="F_Scale" Id="{2e72596d-47d0-4300-958d-56d309a78999}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Scale : INT
VAR_INPUT
	Value:	INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Scale := TO_INT((255.0/32767.0) * TO_REAL(Value));]]></ST>
    </Implementation>
    <LineIds Name="F_Scale">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>